app:
  name: backend
  labels:
    app: backend
  endpoints:
    liveness: /actuator/health
    readiness: /actuator/health
  health:
    probes:
      liveness:
        endpoint: /actuator/health
        initialDelaySeconds: 120
        periodSeconds: 5
      readiness:
        endpoint: /actuator/health
        initialDelaySeconds: 120
        periodSeconds: 5
