/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetUnitsParams = {
symbols?: string[];
sort?: string[];
order_asc?: boolean;
page?: number;
size?: number;
};
