/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TenantDto } from './tenantDto';

export interface PageDtoTenantDto {
  content?: TenantDto[];
  totalElements?: number;
  totalPages?: number;
}
