apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.app.networking.ingress.host }}
    secretName: {{ .Values.app.networking.ingress.host }}-tls
  rules:
  - host: {{ .Values.app.networking.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: /api
        backend:
          service:
            name: app-svc-http
            port:
              number: {{ .Values.app.networking.httpService.port }}
      - pathType: Prefix
        path: /operations
        backend:
          service:
            name: app-svc-http
            port:
              number: {{ .Values.app.networking.httpService.port }}
      - pathType: Prefix
        path: /swagger
        backend:
          service:
            name: app-svc-http
            port:
              number: {{ .Values.app.networking.httpService.port }}
      - pathType: Prefix
        path: /actuator
        backend:
          service:
            name: app-svc-http
            port:
              number: {{ .Values.app.networking.httpService.port }}