apiVersion: v1
kind: Service
metadata:
  name: app-svc-http
spec:
  selector:
    {{ toYaml .Values.app.labels }}
  type: {{ .Values.app.networking.httpService.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.app.networking.httpService.port }}
      targetPort: {{ .Values.app.networking.port.http }}
      {{ if eq .Values.app.networking.httpService.type "NodePort" }}
      nodePort: {{ .Values.app.networking.httpService.nodePort }}
      {{ end }}
