/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetAllParams = {
  ids?: string[];
  names?: string[];
  urls?: string[];
  is_ready?: boolean;
  sort?: string[];
  order_asc?: boolean;
  page?: number;
  size?: number;
  attr?: string[];
};
