/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserDto } from "./userDto";

export interface PageDtoUserDto {
  content?: UserDto[];
  totalElements?: number;
  totalPages?: number;
}
